

#otutab<-read.csv("otu_table_resampled_16S.txt",sep="\t",row.names = 1)
otutab<-read.csv("otu_table_resampled.guilds_ITS.txt",sep="\t",row.names = 1)

treat<-read.csv("treatment info.csv",row.names = 1)
otutab<-otutab[,match(row.names(treat),colnames(otutab))]  ##match samples
sum(row.names(treat)==colnames(otutab))  #check if matached

#iChao1 estimate for each sample
library(SpadeR)
test<-sapply(1:ncol(otutab),function(i){
  message("i=",i)
  all95<-ChaoSpecies(otutab[,i],"abundance",k=10,conf=0.95)
  
  result<-c(t(all95$Species_table[5,]))
  names(result)<-c("estimate","se","95%lower","95%upper")
  result
})

colnames(test)<-colnames(otutab)
result<-t(test)
#write.csv(result,"ichao1_16S_each sample.csv")
write.csv(result,"ichao1_ITS_each sample.csv")


### Test the warming effects by linear mixed model
#read the files generated by the previous step
chao1_bac<-read.csv("ichao1_16S_each sample.csv",row.names = 1)
chao1_fun<-read.csv("ichao1_ITS_each sample.csv",row.names = 1)

sum(row.names(chao1_bac)==row.names(treat)) #check

dat<-data.frame(bacteria_chao1=chao1_bac$estimate,fungi_chao1=chao1_fun$estimate)
year_treat<-paste(treat$year,treat$warm,sep = "_")

## generate mean and se in each year for plot
mean_ses<-sapply(split(dat,year_treat), function(x){
  means<-colMeans(x,na.rm = T)
  sds=sapply(1:ncol(x),function(i){
    sd(x[,i],na.rm = T)
  })
  result<-c(means,sds/(24^0.5))
  result
  
})

test2<-t(mean_ses)
colnames(test2)[3:4]<-c("Bacteria.SE","Fungi.SE")
write.csv(test2,"ichao1_mean and se_WC24samples.csv")

###linear mixed models###
library(lme4)
library(car)
#change the year values to test warming effect in different years
div=data.frame(treat[treat$year==2016,],dat[treat$year==2016,] )


fm1<-lmer(bacteria_chao1~warm*precip*clip+(1|block),data=div)
fm2<-lmer(fungi_chao1~warm*precip*clip+(1|block),data=div)

fm1<-lmer(bacteria_chao1~warm+(1|block),data=div)
fm2<-lmer(fungi_chao1~warm+(1|block),data=div)

summary(fm1)
car::Anova(fm1,type=2)

summary(fm2)
car::Anova(fm2,type=2)